github.com:
    users:
        ArtemOkhotnykIcorna:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: ArtemOkhotnykIcorna
